/**
 * สร้าง state เริ่มต้นสำหรับ Staff Dashboard
 * ข้อมูลจริงจะถูกโหลดจาก Backend ภายใน useStaffDashboard.js
 * MOCK-CLEAN-* และ MOCK-REPAIR-* ใช้ทดสอบหน้าจอเฉพาะฝั่ง Frontend
 */
export function createStaffDashboardData() {
  // ข้อความ สี และเมนูประจำ role เป็น UI configuration ไม่ใช่ข้อมูลจำลอง
  const roleConfig = {
    housekeeper: {
      label: "แม่บ้าน",
      name: "แม่บ้าน",
      staffId: "-",
      avatar: "HK",
      color: "#159a75",
      soft: "#e6f6f1",
      eyebrow: "Housekeeping shift",
      hero: "รับงานจากคิวแม่บ้านร่วม แล้วดูแลงานของตัวเองจนปิดงาน",
      text: "งานทำความสะอาดจากผู้ใช้อาคารจะเข้าคิวแม่บ้านร่วม ทุกคนเห็นได้ แต่ต้องกดรับงานก่อนจึงอัปเดตสถานะและแนบความคืบหน้าได้",
      queue: "คิวรับงานรวมของแม่บ้าน",
      jobTitle: "ศูนย์รับงานรวมของแม่บ้าน",
      jobSubtitle: "กรองตามประเภทที่ผู้ใช้เลือก แล้วรับงานจากคิวกลางของแม่บ้าน",
      primary: "เปิดคิวรับงานแม่บ้าน",
    },
    technician: {
      label: "ช่าง",
      name: "ช่าง",
      staffId: "-",
      avatar: "TC",
      color: "#f97316",
      soft: "#fff0e6",
      eyebrow: "Maintenance shift",
      hero: "รับงานจากคิวช่างร่วม แล้วติดตามการตรวจ ซ่อม และรออะไหล่",
      text: "งานซ่อมจะเข้าคิวช่างร่วมตามประเภทที่ผู้ใช้เลือก ช่างทุกคนเห็นได้และกดรับงานที่เหมาะกับความเชี่ยวชาญของตัวเอง",
      queue: "คิวรับงานรวมของช่าง",
      jobTitle: "ศูนย์รับงานรวมของช่าง",
      jobSubtitle: "กรองประเภทปัญหาที่ผู้ใช้เลือก และรับงานจากคิวกลางของช่าง",
      primary: "เปิดคิวรับงานช่าง",
    },
    clerk: {
      label: "ธุรการ",
      name: "ธุรการ",
      staffId: "-",
      avatar: "OF",
      color: "#2563eb",
      soft: "#e8f0ff",
      eyebrow: "Lost & found desk",
      hero: "อนุมัติหรือไม่อนุมัติรายการ พร้อมจัดการคำขอรับของอย่างเป็นขั้นตอน",
      text: "จัดการของที่รับฝากและประกาศตามหาโดยมีผลอนุมัติหรือไม่อนุมัติชัดเจน พร้อมเปลี่ยนสถานะคำขอรับของและบันทึกเหตุผลทุกครั้ง",
      queue: "รายการที่รออนุมัติและคำขอรับของ",
      jobTitle: "",
      jobSubtitle: "",
      primary: "ตรวจคำขอรับของ",
    },
    admin: {
      label: "แอดมิน",
      name: "แอดมิน",
      staffId: "-",
      avatar: "AD",
      color: "#6757d9",
      soft: "#efedff",
      eyebrow: "Admin command center",
      hero: "เห็นคิวงานทั้งหมด จัดการสิทธิ์ และควบคุมโครงสร้างห้องจากจุดเดียว",
      text: "เข้าถึงงานแม่บ้าน งานช่าง ของหาย–ของได้คืน บัญชี Staff และ QR ห้อง พร้อมมอบหมายหรือแก้ไขข้อมูลตามสิทธิ์แอดมิน",
      queue: "คิวงานรวมที่ยังไม่มีผู้รับผิดชอบ",
      jobTitle: "ศูนย์งานทั้งหมดในระบบ",
      jobSubtitle: "ดูคิวของแม่บ้านและช่าง กรองตามประเภท และจัดการทุกงาน",
      primary: "เปิดศูนย์งานทั้งหมด",
    },
  };

  // ชื่อจริงของผู้ใช้งานปัจจุบันจะถูกแทนค่าจาก buildingCareStaff หลัง login
  const currentUserName = {
    housekeeper: "แม่บ้าน",
    technician: "ช่าง",
    clerk: "ธุรการ",
    admin: "แอดมิน",
  };

  // งานจำลองไม่มี backendId เพื่อให้ทดสอบ flow แบบ local โดยไม่เรียก API ด้วย UUID ปลอม
  const allJobs = [
    {
      id: "MOCK-CLEAN-001",
      type: "cleaning",
      category: "พื้นเปียก/คราบสกปรก",
      title: "พื้นบริเวณโถงชั้น 1 มีคราบน้ำ",
      room: "โถงอาคาร CSB ชั้น 1",
      reporter: "ผู้ใช้งานทดสอบ",
      reporterContact: "tester@example.com",
      time: "เมื่อสักครู่",
      status: "รอรับงาน",
      priority: "เร่งด่วน",
      detail: "พบคราบน้ำใกล้ทางเข้าหลัก กรุณาตรวจสอบและทำความสะอาด",
      assignee: null,
      timeline: [],
      isMock: true,
    },
    {
      id: "MOCK-CLEAN-002",
      type: "cleaning",
      category: "ขยะ/กลิ่น",
      title: "ถังขยะเต็มบริเวณหน้าลิฟต์",
      room: "อาคาร CSB ชั้น 2",
      reporter: "เจ้าหน้าที่อาคาร",
      reporterContact: "building@example.com",
      time: "10 นาทีที่แล้ว",
      status: "รับงานแล้ว",
      priority: "ปกติ",
      detail: "ถังขยะสองจุดเต็มและเริ่มมีกลิ่น",
      assignee: "__CURRENT_HOUSEKEEPER__",
      timeline: [{ title: "รับงาน", detail: "รับจากคิวกลาง", time: "09:10" }],
      isMock: true,
    },
    {
      id: "MOCK-CLEAN-003",
      type: "cleaning",
      category: "ห้องน้ำ/อุปกรณ์สิ้นเปลือง",
      title: "เติมสบู่และกระดาษชำระ",
      room: "ห้องน้ำหญิง ชั้น 3",
      reporter: "ผู้ใช้งานทดสอบ",
      reporterContact: "tester@example.com",
      time: "25 นาทีที่แล้ว",
      status: "กำลังดำเนินการ",
      priority: "ปกติ",
      detail: "สบู่ล้างมือและกระดาษชำระหมด",
      assignee: "__CURRENT_HOUSEKEEPER__",
      note: "กำลังนำอุปกรณ์จากห้องเก็บของ",
      timeline: [
        { title: "รับงาน", detail: "รับจากคิวกลาง", time: "08:50" },
        { title: "อัปเดตสถานะ", detail: "เริ่มดำเนินการ", time: "09:00" },
      ],
      isMock: true,
    },
    {
      id: "MOCK-CLEAN-004",
      type: "cleaning",
      category: "ทำความสะอาดทั่วไป",
      title: "ทำความสะอาดห้องประชุมหลังใช้งาน",
      room: "CSB-201",
      reporter: "เจ้าหน้าที่คณะ",
      reporterContact: "faculty@example.com",
      time: "วันนี้ 08:00",
      status: "เสร็จสิ้น",
      priority: "ปกติ",
      detail: "จัดโต๊ะ เก็บขยะ และเช็ดทำความสะอาดพื้น",
      assignee: "__CURRENT_HOUSEKEEPER__",
      note: "ตรวจพื้นที่เรียบร้อย",
      timeline: [
        { title: "รับงาน", detail: "รับจากคิวกลาง", time: "08:05" },
        { title: "ปิดงาน", detail: "ดำเนินการครบแล้ว", time: "08:40" },
      ],
      isMock: true,
    },
    {
      id: "MOCK-CLEAN-005",
      type: "cleaning",
      category: "ทำความสะอาดทั่วไป",
      title: "เช็ดกระจกประตูทางเข้า",
      room: "ทางเข้าอาคาร CSB",
      reporter: "เจ้าหน้าที่รักษาความปลอดภัย",
      reporterContact: "security@example.com",
      time: "วันนี้ 07:45",
      status: "กำลังดำเนินการ",
      priority: "ปกติ",
      detail: "กระจกมีคราบฝุ่นและรอยนิ้วมือ",
      assignee: "แม่บ้านทดสอบคนอื่น",
      timeline: [],
      isMock: true,
    },
    {
      id: "MOCK-REPAIR-001",
      type: "repair",
      category: "เครื่องปรับอากาศ",
      title: "เครื่องปรับอากาศห้องเรียนไม่เย็น",
      room: "ห้อง CSB-301 ชั้น 3",
      reporter: "ผู้ใช้งานทดสอบ",
      reporterContact: "tester@example.com",
      time: "เมื่อสักครู่",
      status: "รอรับงาน",
      priority: "เร่งด่วน",
      detail: "เปิดเครื่องแล้วมีลมออก แต่ห้องยังไม่เย็น กรุณาตรวจสอบ",
      assignee: null,
      timeline: [],
      isMock: true,
    },
    {
      id: "MOCK-REPAIR-002",
      type: "repair",
      category: "ไฟฟ้า/แสงสว่าง",
      title: "ไฟทางเดินชั้น 2 กะพริบ",
      room: "ทางเดินอาคาร CSB ชั้น 2",
      reporter: "เจ้าหน้าที่อาคาร",
      reporterContact: "building@example.com",
      time: "10 นาทีที่แล้ว",
      status: "รับงานแล้ว",
      priority: "ปกติ",
      detail: "หลอดไฟบริเวณหน้าลิฟต์กะพริบต่อเนื่อง",
      assignee: "__CURRENT_TECHNICIAN__",
      timeline: [{ title: "รับงาน", detail: "รับจากคิวกลาง", time: "09:10" }],
      isMock: true,
    },
    {
      id: "MOCK-REPAIR-003",
      type: "repair",
      category: "ประปา/สุขาภิบาล",
      title: "ก๊อกน้ำอ่างล้างมือรั่ว",
      room: "ห้องน้ำชาย ชั้น 1",
      reporter: "ผู้ใช้งานทดสอบ",
      reporterContact: "tester@example.com",
      time: "25 นาทีที่แล้ว",
      status: "กำลังดำเนินการ",
      priority: "ปกติ",
      detail: "น้ำหยดจากก๊อกตลอดเวลาแม้ปิดสนิทแล้ว",
      assignee: "__CURRENT_TECHNICIAN__",
      note: "กำลังตรวจสอบวาล์วและซีลก๊อกน้ำ",
      timeline: [
        { title: "รับงาน", detail: "รับจากคิวกลาง", time: "08:50" },
        { title: "อัปเดตสถานะ", detail: "เริ่มตรวจสอบจุดรั่ว", time: "09:00" },
      ],
      isMock: true,
    },
    {
      id: "MOCK-REPAIR-004",
      type: "repair",
      category: "อาคาร/เฟอร์นิเจอร์",
      title: "บานพับประตูห้องประชุมหลวม",
      room: "ห้องประชุม CSB-201",
      reporter: "เจ้าหน้าที่คณะ",
      reporterContact: "faculty@example.com",
      time: "วันนี้ 08:00",
      status: "เสร็จสิ้น",
      priority: "ปกติ",
      detail: "ประตูปิดไม่สนิทและมีเสียงดังขณะเปิดปิด",
      assignee: "__CURRENT_TECHNICIAN__",
      note: "ขันบานพับและทดสอบประตูเรียบร้อย",
      timeline: [
        { title: "รับงาน", detail: "รับจากคิวกลาง", time: "08:05" },
        { title: "ปิดงาน", detail: "แก้ไขบานพับแล้ว", time: "08:40" },
      ],
      isMock: true,
    },
    {
      id: "MOCK-REPAIR-005",
      type: "repair",
      category: "ไฟฟ้า/แสงสว่าง",
      title: "ปลั๊กไฟห้องปฏิบัติการใช้งานไม่ได้",
      room: "ห้อง Lab CSB-405",
      reporter: "ผู้ดูแลห้องปฏิบัติการ",
      reporterContact: "lab@example.com",
      time: "วันนี้ 07:45",
      status: "กำลังดำเนินการ",
      priority: "ปกติ",
      detail: "ปลั๊กไฟฝั่งหน้าต่างไม่มีไฟ ต้องตรวจสอบวงจร",
      assignee: "ช่างทดสอบคนอื่น",
      timeline: [],
      isMock: true,
    },
  ];
  const staffData = [];
  const lostSets = {
    inventory: [],
    lostposts: [],
    claims: [],
  };
  const deletedRecords = [];
  const auditHistory = [];
  const workHistory = [
    {
      uid: "MOCK-WH-001",
      staff: "__CURRENT_HOUSEKEEPER__",
      role: "แม่บ้าน",
      itemId: "MOCK-CLEAN-004",
      title: "ทำความสะอาดห้องประชุมหลังใช้งาน",
      category: "ทำความสะอาดทั่วไป",
      action: "ปิดงาน",
      status: "เสร็จสิ้น",
      detail: "จัดโต๊ะ เก็บขยะ และเช็ดพื้นเรียบร้อย",
      date: "2026-09-19",
      time: "08:40",
      isMock: true,
    },
    {
      uid: "MOCK-WH-REPAIR-001",
      staff: "__CURRENT_TECHNICIAN__",
      role: "ช่าง",
      itemId: "MOCK-REPAIR-004",
      title: "บานพับประตูห้องประชุมหลวม",
      category: "อาคาร/เฟอร์นิเจอร์",
      action: "ปิดงาน",
      status: "เสร็จสิ้น",
      detail: "ขันบานพับและทดสอบประตูเรียบร้อย",
      date: "2026-09-19",
      time: "08:40",
      isMock: true,
    },
  ];
  const notificationSets = {
    housekeeper: [
      {
        id: "MOCK-NOTIFICATION-001",
        title: "งานทำความสะอาดเร่งด่วน",
        text: "MOCK-CLEAN-001: พื้นบริเวณโถงชั้น 1 มีคราบน้ำ",
        time: "เมื่อสักครู่",
        unread: true,
        backend: false,
        isMock: true,
      },
    ],
    technician: [
      {
        id: "MOCK-NOTIFICATION-REPAIR-001",
        title: "งานซ่อมเร่งด่วน",
        text: "MOCK-REPAIR-001: เครื่องปรับอากาศห้องเรียนไม่เย็น",
        time: "เมื่อสักครู่",
        unread: true,
        backend: false,
        isMock: true,
      },
    ],
    clerk: [],
    admin: [],
  };
  const announcements = [];

  // ตัวเลือกหมวดหมู่เป็นค่าคงที่ของฟอร์ม ไม่ใช่ข้อมูลรายการ
  const categories = {
    housekeeper: [
      "all",
      "พื้นเปียก/คราบสกปรก",
      "ขยะ/กลิ่น",
      "ห้องน้ำ/อุปกรณ์สิ้นเปลือง",
      "ทำความสะอาดทั่วไป",
    ],
    technician: [
      "all",
      "เครื่องปรับอากาศ",
      "ไฟฟ้า/แสงสว่าง",
      "ประปา/สุขาภิบาล",
      "อาคาร/เฟอร์นิเจอร์",
    ],
    admin: [
      "all",
      "พื้นเปียก/คราบสกปรก",
      "ขยะ/กลิ่น",
      "ห้องน้ำ/อุปกรณ์สิ้นเปลือง",
      "ทำความสะอาดทั่วไป",
      "เครื่องปรับอากาศ",
      "ไฟฟ้า/แสงสว่าง",
      "ประปา/สุขาภิบาล",
      "อาคาร/เฟอร์นิเจอร์",
    ],
  };

  return {
    roleConfig,
    currentUserName,
    allJobs,
    staffData,
    lostSets,
    deletedRecords,
    auditHistory,
    workHistory,
    selectedOverviewStaff: "",
    notificationSets,
    announcements,
    categories,
  };
}
