"""add request id to notifications

Revision ID: 8e077443860d
Revises: 22ee51a25eb0
Create Date: 2026-09-18 16:25:13.588966
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8e077443860d'
down_revision: str | None = '22ee51a25eb0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('request_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_notifications_request_id'), 'notifications', ['request_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'service_requests', ['request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_request_id'), table_name='notifications')
    op.drop_column('notifications', 'request_id')
    # ### end Alembic commands ###
